name: "Pipeline"

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      release-type:
        description: "Type of release (major, minor, patch, alpha)"
        required: true
        default: alpha
        type: choice
        options:
          - major
          - minor
          - patch
          - alpha

jobs:
  continous-integration:
    name: "Continuous Integration"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Format 
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Check types
        run: pnpm types:check

      - name: Test
        run: pnpm test

  continious-deployment:
      if: github.event_name == 'workflow_dispatch'

      name: 'Continous Deployment'
      runs-on: ubuntu-latest
      needs: ['continous-integration']

      steps:
          - uses: actions/checkout@v4

          - uses: pnpm/action-setup@v4
            with:
                version: 9

          - name: Install dependencies
            run: pnpm install

          - name: Build
            run: pnpm build

          - name: Set git configuration 
            run: |
              git config user.name "Animo Solutions"
              git config user.email "development@animo.id"

          - name: Publish
            id: publish
            env:
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

              if [ ${{ inputs.release-type }} == 'alpha' ]; then
                pnpm release --preRelease=alpha
              else
                pnpm release -i=${{ inputs.release-type }}
              fi
